### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 18Markus1984** [SebLague/Slime-Simulation#1]
Hello Sebastian,

I find your YouTube video about the slime simulations and I'm so hyped. It looks like art and it is programming. So I downloaded the file but the problem is that I can't get the unity project running. The screen is always blue. I noticed that the objects for the Simulation were detached, but I couldn't figure the right way that they fit or if there is another detached object. Maybe you have the time to help me or someone else.

Kind Regards
Markus

**Comment by SebLague** [comment]
Hi Markus, I'm not quite sure what you mean about the objects being detached, could you send a screenshot of your view? If the screen is all blue, it's possible you're not in the correct scene, in which case go to the Scenes folder, and open the Slime scene.

**Comment by 18Markus1984** [comment]
Thank you for the really fast answer.
![grafik](https://user-images.githubusercontent.com/52409213/113754765-d9d74700-970f-11eb-8625-2130bdf79428.png)

![grafik](https://user-images.githubusercontent.com/52409213/113754915-03906e00-9710-11eb-8b35-128c1fe543dd.png)

**Comment by 18Markus1984** [comment]
Got it working super cool. Thank you very much for help
