### ISSUE TITLE
Making the background transparent

### ISSUE THREAD

**Issue by FKecac** [SebLague/Slime-Simulation#3]
Is there any way to make the background transparent? To e.g implement the simulation into a Starting screen?

**Comment by Telea-Mihai** [comment]
Yes you can! By using particles/unlit and changing the render mode to transparent, then scroll down to albedo on the color selection option and move the alpha slider down. That works for me, here is a photo with the settings: https://screenrec.com/share/RPbtMuxw7o if it doesnt work ping me.
