### ISSUE TITLE
Slime color change

### ISSUE THREAD

**Issue by RustyNeuron** [SebLague/Slime-Simulation#5]
Hello, Sebastian or anyone reading this, so in the video you can see slime with different colors, how do I change them in the simulation? In the Simulation script I saw an unused colourMapTexture, is this it? Also there are Trail Map, Diffused Trail Map and Display Texture, what do they do? I'm a newbie in Unity, very limited knowledge on shaders and only "ok" programmer, any answers would be appreciated.

**Comment by JaFeRo** [comment]
My experience is only a half step above yours, but I found the proper settings, for you and anyone fiddling around with this cool project. https://imgur.com/a/l0dwCde

**Comment by RustyNeuron** [comment]
> My experience is only a half step above yours, but I found the proper settings, for you and anyone fiddling around with this cool project. https://imgur.com/a/l0dwCde

Yeah, I knew about settings, the format change that you also showed actually doesn't do anything for me unfortunately, but I think it's just a setting for a bit depth and the format of the map or something like that, I don't see how that setting would change color of the simulation on it's own.

**Comment by JaFeRo** [comment]
ok, sorry yeah you are right it does not properly edit the colors as I initially believed when I tested it.

But I found a way to edit the colors here is how I did it:

In the folder "Materials", there is just the file "New Material (Material)". Create a new material and select Material. Under Shader select "Particles", "Standard Unlit". Now you can edit the color of this material, when you are done, under the Simulation select Quad and there you have "Mesh Renderer" where you can select the Material you want to use, select your new one and it changes the color of the simulation. 

*Edit* 
This also works under some very specific conditions I just realized, but it does work if you only use one Element and select the R32G32B32_S Float Format.  https://imgur.com/gallery/DSyAhDH

**Comment by markmacode** [comment]
> but it does work if you only use one Element

Has anyone found a way to change the individual color for multiple slime elements? It would be nice if we could just chose the RGB value for each element in the `Species Settings` on the `Simulation` object.

**Comment by kheremos** [comment]
I've spent a lot of time working with this, and unfortunately it looks like colors are basically hard-coded.  They use the RGB channels as masks, so even if you do figure out how to add different colors, it would change the behavior of the algorithms.  A "mixed color" would have to have a custom detector, and a "pure color" would be partially drawn to a mix color. This is also why you can't really get more than three active species at a time.

I'm not 100% on the above, but at this point it's the conclusion I've reached. Sorry @mark-bromell

**Comment by markmacode** [comment]
Thanks for looking into it @kheremos. I also came to the same conclusion after working on it for a while.

For future reference to anyone exploring this topic -- Currently there is no known **easy** way to change the colors of the slime elements.

**Comment by SebLague** [comment]
Hi, I've just added support for changing colour per species. Let me know if that works for you!

**Comment by pat-mw** [comment]
Hi @SebLague -- I've just tried the new push and for me it seems like the colours don't work. Everything is just black and white despite tinkering with the species settings.

![image](https://user-images.githubusercontent.com/67635701/132137173-248eeb3e-ff83-42f2-b821-ec4b1bbe98b8.png)
![image](https://user-images.githubusercontent.com/67635701/132137181-013754e4-2975-4b19-9650-46bb1301140e.png)

**Comment by markmacode** [comment]
@pat-mw It works for me, but I made some mistakes when testing it out in the beginning. There could be two things happening that I can think of
1. If you're using Linux, make sure that you have Vulkan enabled, Sebastian outlined how to do that [here](https://github.com/SebLague/Slime-Simulation/issues/2#issuecomment-817837275).
2. Make sure that the "Show agents only" setting is unchecked on the `Simulation` object. _When this setting is enabled it removes any extra rendering effects to the slime elements, it only displays them as a single white pixel._

**Comment by kheremos** [comment]
Thanks @SebLague you're amazing!  

I've been trying to turn this into an app that I can share with my young nephew.  He's autistic and I'm hoping that the moving colors and patterns may intrigue him.  Of course, he'll probably just exit the app and open Netflix.  But it still seems worth it.  

Your color solution is elegant, and I'd have responded sooner, but I had to tie it into the UI I've built, so didn't really get to test it until today.  It's excellent.

If I can figure out what's causing some of the render issues people are experiencing, I'll share more advice.  (I think there's some functions that don't work well with OpenGL ES)

Thanks again!

**Comment by pat-mw** [comment]
> @pat-mw It works for me, but I made some mistakes when testing it out in the beginning. There could be two things happening that I can think of
> 
> 1. If you're using Linux, make sure that you have Vulkan enabled, Sebastian outlined how to do that [here](https://github.com/SebLague/Slime-Simulation/issues/2#issuecomment-817837275).
> 2. Make sure that the "Show agents only" setting is unchecked on the `Simulation` object. _When this setting is enabled it removes any extra rendering effects to the slime elements, it only displays them as a single white pixel._

Thanks man! It worked :)

**Comment by SebLague** [comment]
Great, I'm happy it seems to be working! Will close this issue then.
That's really nice @kheremos I hope your nephew enjoys it :)
