### ISSUE TITLE
Screensaver build

### ISSUE THREAD

**Issue by michaelharmonart** [SebLague/Slime-Simulation#6]
This isn't exactly an issue, but rather a strange request for a friend. If you have unity pro or plus could you export builds of just the slime scenes without anything else, to be able to run as a screensaver? You've got stuff to work on but I thought it was an interesting Idea so I'm putting it here. Feel free to close the issue.

**Comment by RustyNeuron** [comment]
Yes, you should be able to disable Unity's splash screen with Unity Plus, Pro, Enterprise.
https://support.unity.com/hc/en-us/articles/212165803-Why-can-I-not-remove-the-Splash-Screen-from-my-build-
