### ISSUE TITLE
Please select a valid startup item...

### ISSUE THREAD

**Issue by Overheal** [SebLague/Slime-Simulation#9]
How do I get this code to run? I'm very novice with Visual Studio.

Bonus: Trying to get the sim to run in a rectangle with all the food along the 2 short sides. Can anyone help with that as well?

**Comment by Theskyspace** [comment]
This code is made possible using a software called unity.
you can download it here [Unity.](https://unity.com/)

**Comment by MoritzMunzinger** [comment]
and then how to proceed?

**Comment by Overheal** [comment]
Yeah had to install unity not just plug unity into VS
